### ISSUE TITLE
Só tem conteúdo até o capitulo 5

### ISSUE THREAD

**Issue by guilhermaker** [lucassimon/flask-api-users#1]
Só tem conteúdo até o capitulo 5. Você pretende continuar com o livro? Estou acompanhando o blog.

**Comment by lucassimon** [comment]
@guilhermaker Lancei novos capitulos. O código fonte atualmente esta na versao 1.0.8 ou na branch capitulo13/dockerfile

**Comment by lucassimon** [comment]
@
